---
- hosts: all
  tasks:
    - name: Install SQLPro for Postgres
      homebrew_cask:
        name: sqlpro-for-postgres
        state: present

    - name: Install Sequel Pro
      homebrew_cask:
        name: sequel-pro
        state: present

    - name: Install Docker Desktop
      homebrew_cask:
        name: docker
        state: present

    - name: Install Github CLI
      homebrew_cask:
        name: gh
        state: present

    - name: Install iTerm2
      homebrew_cask:
        name: iterm2
        state: present
