---
- hosts: local
  tasks:
    - name: Install Neovim
      package:
        name: neovim
        state: latest

    - name: Install RipGrep
      package:
        name: ripgrep
        state: latest

    - name: Install Lazygit
      package:
        name: lazygit
        state: latest

    - name: Install go DiskUsage()
      package:
        name: gdu
        state: latest

    - name: Install Bottom
      package:
        name: bottom
        state: latest

    - name: Clone AstroNvim
      git:
        repo: https://github.com/AstroNvim/AstroNvim.git
        dest: ~/.config/nvim
        clone: yes
        update: yes

    - name: Remove user folder
      file:
        path: ~/.config/nvim/lua/user
        state: absent

    - name: Link user AstroNvim config
      file:
        src: "{{ playbook_dir }}/../../astronvim/user/"
        dest: ~/.config/nvim/lua/user
        state: link
        force: true

    - name: Update neovim plugins
      raw: nvim +AstroUpdatePackages +qa
