---
- hosts: local
  tasks:
    - name: Install Neovim
      package:
        name: neovim
        state: latest

    - name: Install RipGrep
      package:
        name: ripgrep
        state: latest

    - name: Install Lazygit
      package:
        name: lazygit
        state: latest

    - name: Install go DiskUsage()
      package:
        name: gdu
        state: latest

    - name: Install Bottom
      package:
        name: bottom
        state: latest

    - name: Remove astronvim folder
      file:
        path: ~/.config/nvim
        state: absent

    - name: Link AstroNvim config
      file:
        src: "{{ playbook_dir }}/../../astronvim"
        dest: ~/.config/nvim
        state: link
        force: true

    - name: Update neovim plugins
      raw: nvim +AstroUpdatePackages +qa
