---
- hosts: local
  tasks:
    - name: Create ~/.nvm directory
      file:
        path: ~/.nvm
        state: directory

    - name: Install NVM
      shell: >
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
      args:
        executable: /bin/bash
        chdir: "{{ ansible_env.HOME }}"
        creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

    - name: Install Node via NVM
      shell: >
        . {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install {{ item }}
      args:
        executable: /bin/bash
        chdir: "{{ ansible_env.HOME }}"
        creates: "{{ ansible_env.HOME }}/.nvm/versions/{{ item }}"
      loop:
        - node

    - name: Create ~/.pnpm/store directory
      file:
        path: ~/.pnpm/store
        state: directory

    - name: Install Elixir
      package:
        name: elixir
        state: present

    - name: Install Pyenv
      package:
        name: pyenv
        state: present

    - name: Install pipx
      package:
        name: pipx
        state: present

    - name: Install Poetry
      command:
        cmd: pipx install poetry

    - name: Install LuaRocks
      package:
        name: luarocks
        state: present

    - name: Install PostgreSQL
      package:
        name: postgresql
        state: present

    - name: Install Redis
      package:
        name: redis
        state: present

    - name: Install Java
      package:
        name: java
        state: present

    - name: Symlink Java in MacOS
      shell: ln -sfn /usr/local/opt/openjdk/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk.jdk
      become: yes
      when: ansible_distribution == "MacOSX"

    - name: Create ~/.iex_history file on OS X
      file:
        path: ~/.iex_history
        state: touch
      when: ansible_distribution == "MacOSX"

    - name: Install ImageMagick
      package:
        name: imagemagick
        state: present

    - name: Install htop
      package:
        name: htop
        state: present

    - name: Install kubectl
      package:
        name: kubectl
        state: present

    - name: Install k9s cli
      package:
        name: k9s
        state: present

    - name: Install Yandex CLI
      shell: curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
