---
- hosts: local
  tasks:
    - name: Install vim
      package:
        name: vim
        state: present

    - name: Install fzf
      package:
        name: fzf
        state: latest
      
    - name: Install ag on OS X
      package:
        name: the_silver_searcher
        state: latest

    - name: Install Graphviz
      package:
        name: graphviz
        state: latest

    - name: Link .vimrc
      file:
        src: "{{ playbook_dir }}/../../vim/.vimrc"
        path: ~/.vimrc
        state: link
        force: true

    - name: Create ~/.vim directory    
      file:
        path: ~/.vim
        state: directory

    - name: Create ~/.vim/autoload directory
      file:
        path: ~/.vim/autoload
        state: directory
        mode: '0755'

    - name: Create ~/.vim/undodir directory
      file:
        path: ~/.vim/undodir
        state: directory

    - name: Install vim-plug
      get_url:
        dest: ~/.vim/autoload/plug.vim
        url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
        validate_certs: false
        force: yes

    - name: Install all vim plugins
      raw: vim +"PlugInstall" +qa

    - name: Link coc-settings.json
      file:
        src: "{{ playbook_dir }}/../../vim/coc-settings.json"
        path: ~/.vim/coc-settings.json
        state: link
        force: true
