---
- hosts: local
  tasks:
    - name: Install zsh
      package:
        name: zsh
        state: latest

    - name: Install zplug
      git:
        repo: https://github.com/zplug/zplug.git
        dest: "~/.zplug"
        version: master

    - name: Link .zshrc to home directory
      file:
        src: "{{ playbook_dir }}/../../zsh/.zshrc"
        path: "~/.zshrc"
        state: link
        force: true

    - name: Link .zshrc_aliases to home directory
      file:
        src: "{{ playbook_dir }}/../../zsh/.zshrc_aliases"
        path: "~/.zshrc_aliases"
        state: link
        force: true

    - block:
      - name: Check if homebrew zsh is installed
        stat: path=/opt/homebrew/bin/zsh
        register: brew_zsh

      - name: Add homebrew zsh to /etc/shells
        lineinfile: 
          dest=/etc/shells
          line="/opt/homebrew/bin/zsh"
          state=present
        when: brew_zsh.stat.exists

      - user:
          name: "{{ ansible_user_id }}"
          shell: /opt/homebrew/bin/zsh
      become: yes
