[env]
TERM = "xterm-256color"

[general]
import = [
    "./themes/dracula.toml"
]

[window]
padding.x = 4
padding.y = 4

[font]
size = 20

[font.normal]
family = "FiraCode Nerd Font"
style = "Retina"

[font.bold]
family = "FiraCode Nerd Font"
style = "Medium"

[font.italic]
family = "FiraCode Nerd Font"
style = "Light"

[[keyboard.bindings]]
key = "Left"
mods = "Alt"
chars = "\u001bb"

[[keyboard.bindings]]
key = "Right"
mods = "Alt"
chars = "\u001bf"
