---
- hosts: local
  tasks:
    - name: Install OneDrive
      homebrew_cask:
        name: onedrive
        state: present

    - name: Install SQLPro for Postgres
      homebrew_cask:
        name: sqlpro-for-postgres
        state: present

    - name: Install Sequel Pro
      homebrew_cask:
        name: sequel-pro
        state: present

    - name: Install Docker Desktop
      homebrew_cask:
        name: docker
        state: present

    - name: Install Source Tree
      homebrew_cask:
        name: sourcetree
        state: present

    - name: Install iTerm2
      homebrew_cask:
        name: iterm2
        state: present
