---
- hosts: local
  tasks:
    - name: Install OneDrive
      homebrew_cask:
        name: onedrive
        state: present
    - name: Install TeamViewer
      homebrew_cask:
        name: teamviewer
        state: present
