---
- hosts: local
  tasks:
    - name: Install Node
      package:
        name: node
        state: present

    - name: Install Elixir
      package:
        name: elixir
        state: present

    - name: Install PostgreSQL
      package:
        name:  postgresql
        state: present

    - name: Install SQLPro for Postgres
      homebrew_cask:
        name: sqlpro-for-postgres
        state: present

    - name: Install Sequel Pro
      homebrew_cask:
        name: sequel-pro
        state: present

    - name: Install Docker Desktop
      homebrew_cask:
        name: docker
        state: present

