---
- hosts: local
  tasks:
    - name: Install NVM
      shell: >
        curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
      args:
        executable: /bin/bash
        chdir: "{{ ansible_env.HOME }}"
        creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

    - name: Install Node via NVM
      shell: >
        . {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install {{ item }}
      args:
        executable: /bin/bash
        chdir: "{{ ansible_env.HOME }}"
        creates: "{{ ansible_env.HOME }}/.nvm/versions/{{ item }}"
      loop:
        - node

    - name: Install Elixir
      package:
        name: elixir
        state: present

    - name: Install PostgreSQL
      package:
        name:  postgresql
        state: present

    - name: Install Redis
      package:
        name:  redis
        state: present

    - name: Create ~/.iex_history file on OS X
      file:
        path: ~/.iex_history
        state: touch
      when: ansible_distribution == "MacOSX"

    - name: Install ImageMagick
      package:
        name: imagemagick
        state: present

    - name: Install htop
      package:
        name: htop
        state: present

    - name: Install minicube
      package:
        name: minicube
        state: present

    - name: Install kubectl
      package:
        name: kubectl
        state: present

    - name: Install k9s cli
      package:
        name: k9s
        state: present

    - name: Install Yandex CLI
      shell: curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
