---
- hosts: local
  tasks:
    - name: Install Node
      package:
        name: node
        state: present

    - name: Install Elixir
      package:
        name: elixir
        state: present

    - name: Install PostgreSQL
      package:
        name:  postgresql
        state: present

    - name: Create ~/.iex_history file on OS X
      file:
        path: ~/.iex_history
        state: touch
      when: ansible_distribution == "MacOSX"
