---
- hosts: local
  tasks:
    - name: Install vim
      package:
        name: vim
        state: present

    - name: Link ~/.vimrc
      file:
        src: "{{ playbook_dir }}/.vimrc"
        path: ~/.vimrc
        state: link
        force: true

    - name: Create ~/.vim directory    
      file:
        path: ~/.vim
        state: directory

    - name: Create ~/.vim/autoload directory
      file:
        path: ~/.vim/autoload
        state: directory

    - name: Create ~/.vim/undodir directory
      file:
        path: ~/.vim/undodir
        state: directory

    - name: Install vim-plug
      get_url:
        dest: ~/.vim/autoload/plug.vim
        url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
        force: yes

    - name: Install all vim plugins
      raw: vim +PlugInstall +q +q
      
    - name: Install ag for OS X
      package:
        name: the_silver_searcher
        state: latest
      when: ansible_distribution == "MacOSX"
