---
- hosts: local
  tasks:
    - name: Install neovim
      package:
        name: neovim
        state: latest
    - file:
        path: ~/.config/nvim
        state: directory
    - file:
        src: "{{ playbook_dir }}/vim/init.vim"
        path: ~/.config/nvim/init.vim
        state: link
        force: true
    - file:
        path: ~/.vim
        state: directory
    - file:
        src: "{{ playbook_dir }}/vim/UltiSnips"
        path: ~/.vim/UltiSnips
        state: link
        force: true
    - file:
        path: ~/.local/share/nvim/site/autoload
        state: directory
    - get_url:
        dest: ~/.local/share/nvim/site/autoload/plug.vim
        url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
        force: yes
    - name: Install fzf
      package:
        name: fzf
        state: latest
    - name: Install ag
      package:
        name: the_silver_searcher
        state: latest
