---
- hosts: local
  tasks:
    - name: Install neovim
      package:
        name: neovim
        state: latest
    - file:
        path: ~/.config/nvim
        state: directory
    - file:
        src: "{{ playbook_dir }}/vim/init.vim"
        path: ~/.config/nvim/init.vim
        state: link
        force: true
    - file:
        path: ~/.vim
        state: directory
    - file:
        src: "{{ playbook_dir }}/vim/UltiSnips"
        path: ~/.vim/UltiSnips
        state: link

    - file:
        path: ~/.local/share/nvim/site/autoload
        state: directory
    - name: Install vim-plug
      get_url:
        dest: ~/.local/share/nvim/site/autoload/plug.vim
        url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
        force: yes
    - name: Clone fzf repo
      git:
        repo: https://github.com/junegunn/fzf.git
        dest: ~/.fzf
        depth: 1
    - name: Install fzf
      script: ~/.fzf/install
    - name: Install ag for OS X
      package:
        name: the_silver_searcher
        state: latest
      when: ansible_distribution == "MacOSX"
    - name: Install ag for Linux
      package:
        name: silversearcher-ag
      when: ansible_system == "Linux"
    - name: Install all vim plugins
      raw: nvim +PlugInstall +q +q
    - name: Clone nerd font installer
      git:
        repo: https://github.com/ryanoasis/nerd-font.git
        dest: ~/.fonts
        depth: 1
    - file:
        path: ~/.fonts/patched-fonts/
        state: directory
    - name: Unarchive a file that needs to be downloaded (added in 2.0)
      unarchive:
        src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.0.0/Mononoki.zip
        dest: ~/.fonts/patched-fonts/Mononoki
        remote_src: yes
    - name: Install Mononoki font
      script: ~/.fonts/install.sh Mononoki
