---
- hosts: local
  tasks:
    - name: Install neovim
      package:
        name: neovim
        state: latest
    - file:
        path: ~/.config/nvim
        state: directory
    - file:
        src: "{{ playbook_dir }}/vim/init.vim"
        path: ~/.config/nvim/init.vim
        state: link
        force: true
    - file:
        path: ~/.vim
        state: directory
    - file:
        src: "{{ playbook_dir }}/vim/UltiSnips"
        path: ~/.vim/UltiSnips
        state: link
        force: true
    - file:
        path: ~/.local/share/nvim/site/autoload
        state: directory
    - get_url:
        dest: ~/.local/share/nvim/site/autoload/plug.vim
        url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
        force: yes
    - name: Clone fzf
      git:
        repo: https://github.com/junegunn/fzf.git
        dest: ~/.fzf
        depth: 1
    - name: Install fzf
      script: ~/.fzf/install
    - name: Install ag for OS X
      package:
        name: the_silver_searcher
        state: latest
      when: ansible_distribution == "MacOSX"
    - name: Install ag for Linux
      package:
        name: silversearcher-ag
      when: ansible_system == "Linux"
    - name: Install all vim plugins
      raw: nvim +PlugInstall +q +q
