---
- hosts: local
  tasks:
    - name: Install zsh
      package:
        name: zsh
        state: latest
    - file:
        src: "{{ playbook_dir }}/zsh/{{ item }}"
        path: "~/{{ item }}"
        state: link
        force: true
      with_items:
        - .aliases
        - .zshrc
        - .bashrc
    - name: Install oh-my-zsh framework
      raw: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
    - file:
        path: ~/.zzsh/themes
        state: directory
    - file:
        src: "{{ playbook_dir }}/zsh/dracula.zsh-theme"
        path: ~/.oh-my-zsh/themes/dracula.zsh-theme
        state: link
        force: true
    - name: Add zsh to shell
      raw: sudo sh -c "echo $(which zsh) >> /etc/shells"
    - name: Make zsh default shell
      raw: chsh -s $(which zsh)
    - name: Add zsh-suggestions
      raw: git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
