---
- name: Install Neovim for Darwin
  ansible.builtin.include_tasks: tasks_darwin.yml
  when: ansible_os_family == "Darwin"

- name: Install Neovim for Debian
  ansible.builtin.include_tasks: tasks_debian.yml
  when: ansible_os_family == "Debian"

- name: Install Neovim for RedHat
  ansible.builtin.include_tasks: tasks_redhat.yml
  when: ansible_os_family == "RedHat"
