---
- hosts: local
  tasks:
    - name: Install vim
      package:
        name: vim
        state: present
      become: "{{ 'yes' if ansible_system == 'Linux' else 'no' }}"

    - name: Install fzf
      package:
        name: fzf
        state: latest
      become: "{{ 'yes' if ansible_system == 'Linux' else 'no' }}"
      
    - name: Install ag on OS X
      package:
        name: the_silver_searcher
        state: latest
      when: ansible_distribution == "MacOSX"

    - name: Install ag on Linux
      package:
        name: silversearcher-ag
        state: latest
      when: ansible_system == "Linux"
      become: yes

    - name: Install Graphviz
      package:
        name: graphviz
        state: latest

    - name: Link .vimrc
      file:
        src: "{{ playbook_dir }}/.vimrc"
        path: ~/.vimrc
        state: link
        force: true

    - name: Create ~/.vim directory    
      file:
        path: ~/.vim
        state: directory

    - name: Create ~/.vim/autoload directory
      file:
        path: ~/.vim/autoload
        state: directory
        mode: '0755'

    - name: Create ~/.vim/undodir directory
      file:
        path: ~/.vim/undodir
        state: directory

    - name: Install vim-plug
      get_url:
        dest: ~/.vim/autoload/plug.vim
        url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
        force: yes

    - name: Install all vim plugins
      raw: vim +"PlugInstall" +qa

    - name: Link coc-settings.json
      file:
        src: "{{ playbook_dir }}/coc-settings.json"
        path: ~/.vim/coc-settings.json
        state: link
        force: true
