---
- name: "Landing place for neovim download exists."
  ansible.builtin.file:
    state: directory
    owner: root
    group: adm
    mode: "0750"
    path: "{{ neovim_dl_dir }}"

- name: "Ensure neovim appimage downloaded v{{ neovim_version }}"
  ansible.builtin.get_url:
    url: "{{ neovim_appimage_url }}"
    dest: "{{ neovim_dl_dir }}/nvim.appimage"
    mode: "0555"

- name: "Ensure neovim installed v{{ neovim_version }}"
  ansible.builtin.copy:
    src: "{{ neovim_dl_dir }}/nvim.appimage"
    dest: /usr/local/bin/nvim
    owner: root
    group: root
    mode: "0755"
    remote_src: true
