---
- hosts: local
  tasks:
    - name: Install Neovim
      command: snap install nvim --classic
      become: yes

    - name: Install RipGrep
      package:
        name: ripgrep
        state: present

    # TODO Install lazygit
    # https://github.com/jesseduffield/lazygit#ubuntu

    # - name: Install go DiskUsage()
    #   package:
    #     name: gdu
    #     state: present

    # TODO Install go DiskUsage
    # https://github.com/dundee/gdu
    # - name: Install go DiskUsage()
    #   block:
    #   - name: Add ppa:daniel-milde/gdu repository
    #     apt_repository:
    #       repo: ppa:daniel-milde/gdu
    #       state: present
    #       update_cache: yes
    #
    #   - name: Install gdu
    #     package:
    #       name: gdu
    #       state: present
    #   become: yes

    # TODO Install bottom
    # https://github.com/ClementTsang/bottom
    # - name: Install Bottom
    #   command: |
    #     snap connect bottom:mount-observe
    #     snap connect bottom:hardware-observe
    #     snap connect bottom:system-observe
    #     snap connect bottom:process-control
    #   become: yes

    - name: Clone AstroNvim
      git:
        repo: https://github.com/AstroNvim/AstroNvim.git
        dest: ~/.config/nvim
        clone: yes
        update: yes

    - name: Remove user folder
      file:
        path: ~/.config/nvim/lua/user
        state: absent

    - name: Link user AstroNvim config
      file:
        src: "{{ playbook_dir }}/../../astronvim/user/"
        dest: ~/.config/nvim/lua/user
        state: link
        force: true

    - name: Update neovim plugins
      raw: nvim +AstroUpdatePackages +qa
