---
- name: Install lazygit
  ansible.builtin.unarchive:
    src: "{{ lazygit_dl_url }}"
    dest: "{{ lazygit_bin_path }}"
    extra_opts:
      - lazygit
    remote_src: true
    owner: "{{ lazygit_file_owner }}"
    group: "{{ lazygit_file_group }}"
    mode: "{{ lazygit_file_mode }}"
