---
- name: Install Lazygit for Darwin
  ansible.builtin.include_tasks: tasks_darwin.yml
  when: ansible_os_family == "Darwin"

- name: Install Lazygit for Debian
  ansible.builtin.include_tasks: tasks_debian.yml
  when: ansible_os_family == "Debian"

- name: Install Lazygit for RedHat
  ansible.builtin.include_tasks: tasks_redhat.yml
  when: ansible_os_family == "RedHat"
