---
- name: Install AstroNvim
  hosts: local
  tasks:
    - name: Install Neovim
      ansible.builtin.package:
        name: neovim
        state: present

    - name: Install RipGrep
      ansible.builtin.package:
        name: ripgrep
        state: present

    - name: Install go DiskUsage()
      ansible.builtin.package:
        name: gdu
        state: present

    - name: Remove astronvim folder
      ansible.builtin.file:
        path: ~/.config/nvim
        state: absent

    - name: Show playbook dir
      ansible.builtin.debug:
        var: playbook_dir

    - name: Link AstroNvim config
      ansible.builtin.file:
        src: "{{ playbook_dir }}/../../astronvim"
        dest: "{{ ansible_env.HOME }}/.config/nvim"
        state: link
        force: true

- name: Install Lazygit
  ansible.builtin.import_playbook: lazygit/lazygit.yml
