---
- hosts: local
  tasks:
    - homebrew_cask:
        name: hyper
        state: present
    - file:
        src: "{{ playbook_dir }}/.hyper.js"
        path: "~/.hyper.js"
        state: link
        force: true
    - homebrew_tap:
        name: homebrew/cask-fonts
    - homebrew_cask:
        name: font-fira-code
        state: present
