#!/usr/bin/env python3
"""Build generated agent markdown from shared prompts and tool configs."""

from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "config" / "agents"
GENERATED = SOURCE / "generated"
MARKER = "<!-- GENERATED by scripts/build-agents.py. DO NOT EDIT. -->"


def parse_scalar(value: str):
    if value in {"true", "false"}:
        return value == "true"
    if (value.startswith('"') and value.endswith('"')) or (
        value.startswith("'") and value.endswith("'")
    ):
        return value[1:-1]
    return value


def parse_yaml_subset(text: str) -> dict:
    root: dict = {}
    stack: list[tuple[int, dict]] = [(-1, root)]
    for line_no, raw in enumerate(text.splitlines(), 1):
        if not raw.strip() or raw.lstrip().startswith("#"):
            continue
        indent = len(raw) - len(raw.lstrip(" "))
        if indent % 2:
            raise ValueError(f"line {line_no}: indentation must use two spaces")
        line = raw.strip()
        if ":" not in line:
            raise ValueError(f"line {line_no}: expected key: value")
        key, value = line.split(":", 1)
        key = key.strip().strip('"\'')
        value = value.strip()
        while stack[-1][0] >= indent:
            stack.pop()
        parent = stack[-1][1]
        if value == "":
            node: dict = {}
            parent[key] = node
            stack.append((indent, node))
        else:
            parent[key] = parse_scalar(value)
    return root


def quote_key(key: str) -> str:
    safe = all(c.isalnum() or c in "_-" for c in key)
    return key if safe else '"' + key.replace('"', '\\"') + '"'


def quote_value(value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    text = str(value)
    if text in {"true", "false", "null"} or text == "" or text[0] in "*-?:{}[],&#!|>@`\"'":
        return '"' + text.replace('"', '\\"') + '"'
    return text


def emit_yaml(data: dict, indent: int = 0) -> list[str]:
    lines: list[str] = []
    pad = " " * indent
    for key, value in data.items():
        if isinstance(value, dict):
            lines.append(f"{pad}{quote_key(key)}:")
            lines.extend(emit_yaml(value, indent + 2))
        else:
            lines.append(f"{pad}{quote_key(key)}: {quote_value(value)}")
    return lines


def agent_dirs() -> list[Path]:
    return sorted(
        p for p in SOURCE.iterdir() if p.is_dir() and p.name not in {"generated", "claude"}
    )


def render(agent: Path, target: str) -> str:
    config_file = agent / f"{target}.yml"
    prompt_file = agent / "prompt.md"
    config = parse_yaml_subset(config_file.read_text())
    prompt = prompt_file.read_text().strip() + "\n"
    if target == "claude":
        return "\n".join(["---", *emit_yaml(config), "---", "", prompt])
    return "\n".join(["---", *emit_yaml(config), "---", "", MARKER, "", prompt])


def write_or_check(path: Path, content: str, check: bool) -> bool:
    if check:
        old = path.read_text() if path.exists() else ""
        if old == content:
            return True
        diff = "".join(
            difflib.unified_diff(
                old.splitlines(True),
                content.splitlines(True),
                fromfile=str(path),
                tofile=str(path),
            )
        )
        sys.stderr.write(diff)
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    return True


def build(targets: list[str], check: bool) -> int:
    ok = True
    for target in targets:
        out_dir = GENERATED / target / "agents"
        for agent in agent_dirs():
            ok = write_or_check(out_dir / f"{agent.name}.md", render(agent, target), check) and ok
    return 0 if ok else 1


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--target", choices=["opencode", "claude", "all"], default="all")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    targets = ["opencode", "claude"] if args.target == "all" else [args.target]
    return build(targets, args.check)


if __name__ == "__main__":
    raise SystemExit(main())
