---
- hosts: local
  tasks:
    # Move out somewhere
    - name: Install zsh and zplu
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - zsh
        - zplug

    - name: Link .zshrc to home directory
      file:
        src: "{{ playbook_dir }}/.zshrc"
        path: "~/.zshrc"
        state: link
        force: true

    - block:
      - name: Check if homebrew zsh is installed
        stat: path=/opt/homebrew/bin/zsh
        register: brew_zsh

      - name: Add homebrew zsh to /etc/shells
        lineinfile: 
          dest=/etc/shells
          line="/opt/homebrew/bin/zsh"
          state=present
        when: brew_zsh.stat.exists

      - user:
          name: "{{ ansible_user_id }}"
          shell: /opt/homebrew/bin/zsh
      become: yes
