# Prefix
unbind C-b
set -g prefix C-a
set -g prefix2 None
bind C-a send-prefix

# Reload config
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Reloaded tmux config"

# Vi mode
setw -g mode-keys vi

# Vi pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Status
set -g status-position top

# TPM plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'dracula/tmux'

# Dracula
set -g @dracula-show-powerline true
set -g @dracula-fixed-location "Berlin, Germany"
set -g @dracula-plugins "weather"
set -g @dracula-show-flags true
set -g @dracula-left-icon session
set -g @dracula-show-fahrenheit false

# Initialize TPM. Keep final.
run '~/.config/tmux/plugins/tpm/tpm'
