---
- name: Install Ghostty for macOS
  ansible.builtin.include_tasks: tasks_darwin.yml
  when: ansible_os_family == "Darwin"

- name: Install Ghostty for Linux
  ansible.builtin.include_tasks: tasks_linux.yml
  when: ansible_os_family != "Darwin"

- name: Link Ghostty config directory
  ansible.builtin.file:
    src: "{{ ghostty_source_dir }}"
    dest: "{{ ghostty_config_dir }}"
    state: link
    force: true
